config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :messages
  resources :comments
  resources :product_types
  resources :products
  resources :shops
  resources :sellers
  resources :favorites
  resources :cart_items
  resources :order_items
  resources :orders
  resources :addresses
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # user part
  get 'user_info', to: 'user_views#user_info'
  get 'user_image_update', to: 'user_views#user_image_update'
  post 'do_user_image_update', to: 'user_views#do_user_info_update'
  get 'login', to: 'user_views#login'
  post 'do_login', to: 'user_views#do_login'
  get 'register', to: 'user_views#register'
  post 'do_register', to: 'user_views#do_register'
  get 'logout', to: 'user_views#logout'
  get 'add_to_cart/:id', to: 'user_views#add_to_cart', as: :add_to_cart
  get 'cart', to: 'user_views#cart', as: :my_cart
  get 'add_cart_num/:id', to: 'user_views#add_cart_num', as: :add_cart_num
  get 'decrease_cart_num/:id', to: 'user_views#decrease_cart_num', as: :decrease_cart_num
  get 'follow/:id', to: 'user_views#follow', as: :follow_shop
  get 'unfollow/:id', to: 'user_views#unfollow', as: :unfollow_shop
  get 'my_favorites', to: 'user_views#favorites', as: :user_favorites
  get 'favorite/:id', to: 'user_views#favorite', as: :favorite_product
  get 'unfavorite/:id', to: 'user_views#unfavorite', as: :unfavorite_product
  get 'product/:id', to: 'user_views#product', as: :user_product
  get 'checkout', to: 'user_views#checkout', as: :user_checkout
  post 'gen_order', to: 'user_views#gen_order', as: :user_gen_order
  get 'place_order_success', to: 'user_views#place_order_success', as: :place_order_success
  get 'my_orders/:order_status', to: 'user_views#my_orders', as: :my_orders
  get 'receive/:order_id', to: 'user_views#receive_product', as: :receive_product
  post 'user_comment/:pid', to: 'user_views#comment', as: :user_comment
  get 'finish_order/:order_id', to: 'user_views#finish_order', as: :finish_order
  get 'my_messages', to: 'user_views#my_messages', as: :my_messages
  get 'delete_message/:id', to: 'user_views#my_message_delete', as: :user_message_delete
  get 'shop_info/:id', to: 'user_views#shop_info', as: :user_shop_info
  get 'system_detail', to: 'user_views#system_detail'
  get 'clear', to: 'user_views#database_clear'

  # shop part
  get 'shop', to: 'shop_views#shop_info', as: :shop_root
  get 'shop/login', to: 'shop_views#login'
  post 'shop/do_login', to: 'shop_views#do_login'
  get 'shop/register', to: 'shop_views#register'
  post 'shop/do_register', to: 'shop_views#do_register'
  get 'shop/logout', to: 'shop_views#logout'
  get 'shop/shop_register', to: 'shop_views#shop_register'
  post 'shop/do_shop_register', to: 'shop_views#do_shop_register'
  get 'shop/info', to: 'shop_views#shop_info'
  get 'shop/product_list', to: 'shop_views#product_list'
  post 'shop/add_product', to: 'shop_views#add_product'
  get 'shop/product_type', to: 'shop_views#product_types'
  get 'shop/show/:id', to: 'shop_views#product', as: :show_product
  get 'shop/orders/:order_status', to: 'shop_views#my_orders', as: :shop_orders
  get 'shop/my_messages', to: 'shop_views#my_messages', as: :shop_messages
  get 'shop/ship_product/:order_id', to: 'shop_views#ship_product', as: :ship_product
  get 'shop/urge_comment/:order_id', to: 'shop_views#urge_comment', as: :urge_comment
  get 'shop/product_image_update/:id', to: 'shop_views#product_image_update', as: :product_image_update
  post 'shop/do_product_image_update/:id', to: 'shop_views#do_product_image_update', as: :do_product_image_update
  get 'shop/shop_image_update', to: 'shop_views#shop_image_update'
  post 'shop/do_shop_image_update', to: 'shop_views#do_shop_image_update'


  root to: "user_views#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  has_many :order_items
  belongs_to :shop
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_type
  belongs_to :shop
  has_many :favorites
  has_many :cart_items
  has_many :order_items
  has_many :comments
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :product
end

app/models/seller.rb
class Seller < ApplicationRecord
  has_one :shop
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :seller
  has_many :products
  has_many :follows
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  has_many :addresses
  has_many :orders
  has_many :cart_items
  has_many :comments
  has_many :messages
  has_many :favorites
  has_many :follows
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    seller = Seller.where(id:session[:current_sellerid]).first
    @shop.seller = seller
    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_info_path, notice: '商店信息修改成功。' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :address, :description, :telephone)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>商店信息更改</h1>

<%= render 'form', shop: @shop %>

<%= link_to '返回', shop_info_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.address %></td>
        <td><%= shop.description %></td>
        <td><%= shop.telephone %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shop.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @shop.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shop.description %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @shop.telephone %>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>