config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :messages
  resources :comments
  resources :product_types
  resources :products
  resources :shops
  resources :sellers
  resources :favorites
  resources :cart_items
  resources :order_items
  resources :orders
  resources :addresses
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # user part
  get 'user_info', to: 'user_views#user_info'
  get 'user_image_update', to: 'user_views#user_image_update'
  post 'do_user_image_update', to: 'user_views#do_user_info_update'
  get 'login', to: 'user_views#login'
  post 'do_login', to: 'user_views#do_login'
  get 'register', to: 'user_views#register'
  post 'do_register', to: 'user_views#do_register'
  get 'logout', to: 'user_views#logout'
  get 'add_to_cart/:id', to: 'user_views#add_to_cart', as: :add_to_cart
  get 'cart', to: 'user_views#cart', as: :my_cart
  get 'add_cart_num/:id', to: 'user_views#add_cart_num', as: :add_cart_num
  get 'decrease_cart_num/:id', to: 'user_views#decrease_cart_num', as: :decrease_cart_num
  get 'follow/:id', to: 'user_views#follow', as: :follow_shop
  get 'unfollow/:id', to: 'user_views#unfollow', as: :unfollow_shop
  get 'my_favorites', to: 'user_views#favorites', as: :user_favorites
  get 'favorite/:id', to: 'user_views#favorite', as: :favorite_product
  get 'unfavorite/:id', to: 'user_views#unfavorite', as: :unfavorite_product
  get 'product/:id', to: 'user_views#product', as: :user_product
  get 'checkout', to: 'user_views#checkout', as: :user_checkout
  post 'gen_order', to: 'user_views#gen_order', as: :user_gen_order
  get 'place_order_success', to: 'user_views#place_order_success', as: :place_order_success
  get 'my_orders/:order_status', to: 'user_views#my_orders', as: :my_orders
  get 'receive/:order_id', to: 'user_views#receive_product', as: :receive_product
  post 'user_comment/:pid', to: 'user_views#comment', as: :user_comment
  get 'finish_order/:order_id', to: 'user_views#finish_order', as: :finish_order
  get 'my_messages', to: 'user_views#my_messages', as: :my_messages
  get 'delete_message/:id', to: 'user_views#my_message_delete', as: :user_message_delete
  get 'shop_info/:id', to: 'user_views#shop_info', as: :user_shop_info
  get 'system_detail', to: 'user_views#system_detail'
  get 'clear', to: 'user_views#database_clear'

  # shop part
  get 'shop', to: 'shop_views#shop_info', as: :shop_root
  get 'shop/login', to: 'shop_views#login'
  post 'shop/do_login', to: 'shop_views#do_login'
  get 'shop/register', to: 'shop_views#register'
  post 'shop/do_register', to: 'shop_views#do_register'
  get 'shop/logout', to: 'shop_views#logout'
  get 'shop/shop_register', to: 'shop_views#shop_register'
  post 'shop/do_shop_register', to: 'shop_views#do_shop_register'
  get 'shop/info', to: 'shop_views#shop_info'
  get 'shop/product_list', to: 'shop_views#product_list'
  post 'shop/add_product', to: 'shop_views#add_product'
  get 'shop/product_type', to: 'shop_views#product_types'
  get 'shop/show/:id', to: 'shop_views#product', as: :show_product
  get 'shop/orders/:order_status', to: 'shop_views#my_orders', as: :shop_orders
  get 'shop/my_messages', to: 'shop_views#my_messages', as: :shop_messages
  get 'shop/ship_product/:order_id', to: 'shop_views#ship_product', as: :ship_product
  get 'shop/urge_comment/:order_id', to: 'shop_views#urge_comment', as: :urge_comment
  get 'shop/product_image_update/:id', to: 'shop_views#product_image_update', as: :product_image_update
  post 'shop/do_product_image_update/:id', to: 'shop_views#do_product_image_update', as: :do_product_image_update
  get 'shop/shop_image_update', to: 'shop_views#shop_image_update'
  post 'shop/do_shop_image_update', to: 'shop_views#do_shop_image_update'


  root to: "user_views#index"
end

app/controllers/shop_views_controller.rb
class ShopViewsController < ApplicationController
  before_action :authenticate, except: [:login, :register, :do_login, :do_register]

  def login
  end

  def do_login
    print(params)
    seller = Seller.where(username: params[:username], password: params[:password]).first
    if seller
      session[:current_sellerid] = seller.id
      shop = Shop.where(seller_id: seller.id).first
      if shop
        session[:current_shopid] = shop.id
        redirect_to shop_info_path, notice: '卖家登录成功。'
      else
        redirect_to shop_shop_register_path, notice: '需要完善信息。'
      end
    else
      redirect_to shop_login_path, alert: '用户名或密码错误。'
    end
  end

  def register
  end

  def do_register
    username = params[:username]
    email = params[:email]
    password = params[:password]
    password_confirm = params[:password_confirm]

    print(username)
    print(email)
    print(password)
    print(password_confirm)
    if username.empty? or email.empty? or password.empty? or password_confirm.empty?
      redirect_to register_url, alert: '信息不能为空。' and return
    end
    seller = Seller.where(username:username).first
    print(seller)
    if seller
      redirect_to shop_register_url, alert: '用户名已存在。' and return
    end
    unless password_confirm == password
      redirect_to shop_register_url, alert: '密码不匹配。' and return
    end
    seller = Seller.new
    seller.username = username
    seller.email = email
    seller.password = password
    seller.save
    redirect_to shop_login_path, notice: '卖家注册成功，请登录。'
  end

  def logout
    session.delete(:current_sellerid)
    session.delete(:current_shopid)
    redirect_to shop_login_path, alert: '卖家退出成功。'
  end

  def shop_register
  end

  def do_shop_register
    name = params[:name]
    address = params[:address]
    description = params[:description]
    phone = params[:phone]
    print(name)
    print(address)
    print description
    print phone
    shop = Shop.new
    shop.name = name
    shop.address = address
    shop.description = description
    shop.telephone = phone
    shop.seller_id = session[:current_sellerid]
    shop.save
    session[:current_shopid] = shop.id
    redirect_to shop_info_path, notice: '商店信息已经完善。'
  end

  def shop_info
    seller_id = session[:current_sellerid]
    @seller = Seller.where(id:seller_id).first
    @shop = Shop.where(seller_id: seller_id).first
    @image = @shop.image.nil?
  end

  def shop_image_update
    shop_id = session[:current_shopid]
    @shop = Shop.where(id:shop_id).first
    render 'image_update'
  end

  def do_shop_image_update
    shop_id = session[:current_shopid]
    @shop = Shop.where(id:shop_id).first
    uploaded_file = params[:picture]
    File.open(Rails.root.join('app', 'assets', 'images', uploaded_file.original_filename), 'wb') do |file|
      file.write(uploaded_file.read)
    end
    puts uploaded_file
    @shop.image = uploaded_file.original_filename
    @shop.save
    redirect_to shop_info_path, notice: '商店图表修改成功。'
  end

  def add_product
    name = params[:name]
    price = params[:price]
    description = params[:description]
    stock = params[:stock]
    type = params[:type]
    print name, price, description, stock, type
    ptype = ProductType.where(name: type).first

    product = Product.new
    product.name = name
    product.price = price
    product.stock = stock
    product.sales = 0
    product.image = 'no_image.png'
    product.description = description
    product.product_type = ptype
    product.shop_id = session[:current_shopid]
    product.save
    redirect_to shop_product_list_path, notice: '添加商品成功。'
  end

  def product_list
    shop_id = session[:current_shopid]
    @types = ProductType.all
    @products = Product.where(shop_id: shop_id)
  end

  def product
    @product = Product.find(params[:id])
    @image = @product.image.nil?
  end

  def product_image_update
    @product = Product.find(params[:id])
    render 'upload_image.html.erb'
  end

  def do_product_image_update
    @product = Product.find(params[:id])
    uploaded_file = params[:picture]
    File.open(Rails.root.join('app', 'assets', 'images', uploaded_file.original_filename), 'wb') do |file|
      file.write(uploaded_file.read)
    end
    puts uploaded_file
    @product.image = uploaded_file.original_filename
    @product.save
    redirect_to show_product_path(@product), notice: '商品图片修改成功。'
  end

  def my_orders
    shop_id = session[:current_shopid]
    order_status = params[:order_status].to_i
    case order_status
    when 5
      @orders = Order.where(shop_id: shop_id)
    when 0
      @orders = Order.where(shop_id: shop_id, order_status: 0)
    when 1
      @orders = Order.where(shop_id: shop_id, order_status: 1)
    when 2
      @orders = Order.where(shop_id: shop_id, order_status: 2)
    when 3
      @orders = Order.where(shop_id: shop_id, order_status: 3)
    else
      @orders = nil
    end
    if @orders.blank?
      @no_order = true
    else
      @no_order = false
    end
  end

  def my_messages
    shop_id = session[:current_shopid]
    @messages = Message.where(shop_id: shop_id, message_type: 2)
  end

  def ship_product
    order_id = params[:order_id]
    order = Order.where(id: order_id).first
    order.order_status = 1
    order.save
    message = Message.new
    message.message_type = 1
    message.create_date = Time.now
    message.user_id = order.user_id
    message.shop_id = order.shop_id
    message.content = ''
    message.save
    redirect_to request.referer, notice: '发货成功。'
  end

  def urge_comment
    order_id = params[:order_id]
    order = Order.where(id: order_id).first
    message = Message.new
    message.message_type = 1
    message.create_date = Time.now
    message.user_id = order.user_id
    message.shop_id = order.shop_id
    message.content = '你有一件商品需要评价。'
    message.save
    redirect_to request.referer, notice: '催促评价成功。'
  end

  def product_types
    @product_types = ProductType.all
  end

  def authenticate
    redirect_to shop_login_path, alert: 'Must login!' unless session[:current_sellerid]
  end

end

app/helpers/shop_views_helper.rb
module ShopViewsHelper
end

app/views/shop_views/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= shop_info_path %>">商店面板</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><a href="<%= shop_product_list_path %>">全部商品</a></li>
        <li><a href="<%= shop_product_type_path %>">商品类别</a></li>
        <li><a href="<%= shop_orders_path(5) %>">全部订单</a></li>
        <li><a href="<%= shop_messages_path %>">全部消息</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            操作
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% if session[:current_sellerid] %>
              <li><a href="<%= shop_logout_path %>">登出</a></li>
            <% else %>
              <li><a href="<%= shop_login_path %>">登录</a></li>
              <li><a href="<%= shop_register_path %>">注册</a></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <% unless notice.nil? %>
    <div id="myAlert" class="alert alert-success">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <%= notice %>
    </div>
  <% end %>
</div>

app/views/shop_views/image_update.html.erb
<%= render 'nav' %>
<%= form_with url: shop_do_shop_image_update_path, multipart: true do %>
  <%= file_field_tag :picture %>
  <%= submit_tag '修改' %>
<% end %>

app/views/shop_views/login.html.erb
<style>
    body {

        background-repeat: no-repeat;
        background-size: 100%;
        background-position: 0 -300px;

    }
</style>

<main style="margin-top: 150px;">
  <div class="container">
    <div class="row">
      <!-- <div class="col-md-8">
          <img src="../images/login/pngsucai_324660_8e29d5.png" alt="">
      </div> -->

      <div class="col-md-4 col-md-offset-4"
           style="border: 1px solid #ddd; border-radius: 2%; background-color: rgb(253, 252, 252);">
        <p id="notice"><%= notice %></p>

        <h3 style="text-align: center; margin-bottom: 20px;">欢迎登录</h3>

        <div id="prompt">

        </div>
        <h3><%= alert %></h3>
        <%= form_with url: shop_do_login_path do %>
          <p>
            用户名: <%= text_field_tag :username %>
          </p>
          <p>
            密码: <%= password_field_tag :password %>
          </p>
          <%= submit_tag '登录' %>
        <% end %>

        <p>还没有账号？ <a href="<%= shop_register_url %>">注册一个</a></p>
      </div>
    </div>
  </div>
  </div>
</main>

app/views/shop_views/my_messages.html.erb
<%= render 'nav' %>
<main class="container-fluid">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="page-header">
      <h2>
        我的消息
      </h2>
    </div>
    <table class="table table-hover">
      <thead>
      <tr>
        <th width="5%"></th>
        <th width="80%"></th>
        <th width="15%"></th>
      </tr>
      </thead>
      <tbody>
      <% for message in @messages %>
        <tr>
          <td><%= image_tag message.user.image, size: '75x75' %></td>
          <td><h4><%= message.user.nickname %></h4>
            <h5><%= message.content %></h5>
            <p>time:<%= message.create_date %></p></td>
          <td><%= link_to '删除', user_message_delete_path(message) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>


  </div>
  <div class="col-sm-2"></div>

</main>

app/views/shop_views/my_orders.html.erb
<%= render 'nav' %>
<main class="container-fluid">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">

    <div class="col-sm-12" style="margin-top: 30px">
      <h3 class="title">我的订单</h3>
      <hr>

    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-primary" onclick="window.location.href='<%= shop_orders_path(5) %>'">全部订单</button>
      <button type="button" class="btn btn-primary" onclick="window.location.href='<%= shop_orders_path(0) %>'">待发货</button>
      <button type="button" class="btn btn-primary" onclick="window.location.href='<%= shop_orders_path(1) %>'">已发货</button>
      <button type="button" class="btn btn-primary" onclick="window.location.href='<%= shop_orders_path(2) %>'">待评论</button>
      <button type="button" class="btn btn-primary" onclick="window.location.href='<%= shop_orders_path(3) %>'">已完成</button>
    </div>
    <% if @no_order %>
      <h4>暂时没有订单</h4>
    <% else %>
      <div class="tab-content">
        <div class="tab-pane active" id="panel-all">
          <table class="table">
            <thead>
            <tr>
              <th colspan="3">商品信息</th>
              <th>单价</th>
              <th>数量</th>
              <th>实付款</th>
              <th>交易状态</th>
              <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <% for order in @orders %>
              <tr>
                <td colspan="8" style="border: 0"></td>
              </tr>
              <tr>
                <td colspan="8" style="text-align: left;background-color: rgb(190, 224, 229)">
                  <div class="col-md-3">
                    订单编号：<span><%= order.order_id %></span>
                  </div>
                  <div class="col-md-6">
                    下单时间：<span><%= order.order_date %></span>
                  </div>
                  <div class="col-md-3 ">
                    下单用户: <span><%= order.user.nickname %></span>
                  </div>
                </td>
              </tr>
              <% for order_item in order.order_items %>
                <tr data-status="to-comment">
                  <td width="10%">
                    <a href="<%= show_product_path(order_item.product) %>"><img src="<%= image_url order_item.product.image%>" width="60" height="60" alt=""></a>
                  </td>
                  <td width="10%"><%= order_item.product.name %></td>
                  <td width="30%"><%= order_item.product.description %></td>
                  <td width="10%">￥<span><%= order_item.product.price %></span></td>
                  <td width="8%"><%= order_item.product_number %></td>
                  <td width="10%">￥<span><%= order_item.product.price * order_item.product_number %></span> </td>
                  <td width="10%" class="status">
                    <% if order.order_status == 0 %>
                      待发货
                    <% elsif order.order_status == 1%>
                      未收货
                    <% elsif order.order_status == 2%>
                      未评价
                    <% elsif order.order_status == 3%>
                      已完成
                    <% end %>
                  </td>
                  <td width="12%">
                    <% if order.order_status == 0 %>
                      <button type="button" class="btn btn-success"
                              data-toggle="modal" data-target="#exampleModal"
                              onclick="window.window.location.href='<%= ship_product_path(order) %>'">
                        发货
                      </button>
                    <% elsif order.order_status == 1%>
                      <button type="button" class="btn btn-default"
                              disabled="disabled">
                        待收货
                      </button>
                    <% elsif order.order_status == 2%>
                      <button type="button" class="btn btn-primary"
                              data-toggle="modal" data-target="#exampleModal"
                              onclick="window.window.location.href='<%= urge_comment_path(order) %>'">
                        催一下
                      </button>
                    <% elsif order.order_status == 3%>
                      <button type="button" class="btn btn-default"
                              disabled="disabled">
                        已完成
                      </button>
                    <% end %>

                  </td>
                </tr>
              <% end %>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
  </div>
  <div class="col-sm-2"></div>

</main>

app/views/shop_views/product.html.erb
<style>
    .img-frame {
        position: relative;
        width: 100%;
        padding-top: 100%;
        /* 宽高比例为1：1 */
    }

    .img-frame img {
        position: absolute;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
    }

    #good-img {
        width: 100%;
        height: 100%;
        border: 1px wheat solid;
    }

    .avatar {
        width: 60%;
        border-radius: 50%;
        border: 1px wheat solid;
    }

    .commenter {
        color: cadetblue;
        font-size: large;
        font-weight: bold;
    }

    .comment {
        margin-top: 10px;
        font-size: 100%;
        line-height: 140%;
    }

    .comment-time {
        margin-top: 10px;
        color: #bbb;
    }
</style>
<%= render 'nav' %>
<main class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <hr>
        <div class="row">
          <div class="col-md-6">
            <div class="img-frame">
              <% if @image %>
                <%= image_tag 'no_image.png' %>
              <% else %>
                <%= image_tag @product.image %>
              <% end %>
            </div>
          </div>

          <div class="col-md-5 col-md-offset-1">
            <h3 id="good-name"><%= @product.name %></h3>
            <hr>
            <div style="color: red;">
              ￥ <span id="unit-price"><%= @product.price %></span>
            </div>


            <hr>
            <div id="good-descrip"><%= @product.description %></div>
            <hr>
            库存<span id="inventory"><%= @product.stock %></span>件
            <hr>
            销量<span id="inventory"><%= @product.sales %></span>件
            <hr>

            <hr>

            <button class="btn btn-success col-md-5"
                    onclick="window.window.location.href='<%= product_image_update_path(@product) %>'">
              修改图片</button>
          </div>
        </div>
        <hr>

        <div style="margin-top: 60px; margin-bottom: 10px; font-size: large;">
          全部评价
        </div>
        <div class="row" style="margin-top: 0px;">
          <table class="table" id="comment-table"
                 style="table-layout:fixed ;border-bottom: 1px solid #ddd;">
            <thead>
            <tr>
              <th width="10%"></th>
              <th width="85%"></th>
              <th width="5%"></th>
            </tr>
            </thead>
            <tbody>
            <% for comment in @product.comments %>
              <tr>
                <td style="text-align: center;">
                  <%= image_tag comment.user.image, class: 'avatar' %>
                </td>
                <td>
                  <div style="padding-left: 1em;">
                    <div class="commenter"><%= comment.user.username %></div>
                    <div class="comment">
                      <%= comment.content %>
                    </div>
                    <div class="comment-time"><%= comment.create_date %></div>
                  </div>
                </td>
                <td style="text-align: center;">
                  <%= link_to '删除', comment, method: :delete, data: { confirm: '确定删除这条评论吗?' }, class: 'btn btn-danger' %>
                </td>
              </tr>
            <% end %>

            </tbody>
          </table>
        </div>

      </div>

    </div>

  </div>

</main>

app/views/shop_views/product_list.html.erb
<%= render 'nav' %>

<main class="container-fluid">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="page-header">
      <h2>
        全部商品
        <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">添加新商品</button>
      </h2>
    </div>

    <div class="col-md-12">
      <table class="table" style="table-layout:fixed ; ">
        <thead>
        <tr>
          <th style="width: 10%;"></th>
          <th style="width: 10%;">名称</th>
          <th style="width: 10%;">类别</th>
          <th style="width: 10%;">价格</th>
          <th style="width: 10%;">库存</th>
          <th style="width: 10%;">销量</th>
          <th style="width: 8%;">编辑</th>
          <th style="width: 10%;">详情</th>
          <th style="width: 8%;">操作</th>
          <th style="width: 8%;">优惠</th>
          <th style="width: 8%;">删除</th>
        </tr>
        </thead>
        <tbody style="height: 60px; overflow-y: auto;">
        <% @products.each do |product| %>
        <tr data-id="{{ product.id }}">
          <td>
            <!-- <a href="/shop/product/{{ product.id }}/"></a> -->
            <div class="img-frame">
              <%= image_tag product.image, size: '75x75' %>
            </div>
          </td>
          <td style="word-wrap:break-word;" class="good-name"><%= product.name %></td>
          <td style="word-wrap:break-word;" class="good-type"><%= product.product_type.name %></td>
          <td class="unit-price">￥<span><%= product.price %></span> </td>
          <td class="inventory"><%= product.stock %></td>
          <td><%= product.sales %></td>
          <td><button type=" button" class="btn  btn-warning"
                      data-toggle="modal" data-target="#modify-good-modal"
                      onclick="window.location.href='<%= edit_product_path(product) %>'">编辑</button>
          </td>
          <td><button type=" button" class="btn  btn-info"
                      onclick="window.location.href='<%= show_product_path(product) %>'">查看详情</button>
          </td>
          <td><button type="button" class="btn  btn-default " disabled="disabled"
                      onclick="window.location.href='/shop/product_state_change/up/?id={{ product.id }}'">上架</button>
          </td>
          <td>
            <button type=" button" class="btn btn-default"
                    disabled="disabled">优惠</button>
          </td>
          <td><%= link_to '删除', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>


        </tr>
        <% end %>

        </tbody>
      </table>
    </div>

    <!-- 模态框（Modal） -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">

        <div class="modal-content">
          <%= form_with url: shop_add_product_path do %>
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title" id="myModalLabel">add product</h4>
            </div>
            <div id="prompt">

            </div>
            <div class="col-md-10 col-md-offset-1">

              <div class="form-group">
                <label class="control-label">product name</label>
                <%= text_field_tag :name, nil, class:"form-control"%>
              </div>
              <div class="form-group">
                <label class="control-label">product price</label>
                <%= text_field_tag :price, nil, class:"form-control"%>
              </div>
              <div class="form-group">
                <label class="control-label">product description</label>
                <%= text_field_tag :description, nil, class:"form-control"%>
              </div>
              <div class="form-group">
                <label class="control-label">product stock</label>
                <%= text_field_tag :stock, nil, class:"form-control"%>
              </div>
              <div class="form-group">
                <label class="control-label">product type</label>

                <select class="form-control" name="type">
                  <% for t in @types %>
                    <option><%= t.name %></option>
                  <% end %>
                </select>

              </div>


            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
              <%= submit_tag '添加', class: "btn btn-success" %>
            </div>

          <% end %>
        </div><!-- /.modal-content -->
      </div><!-- /.modal -->
    </div>
  </div>
  <div class="col-sm-2"></div>

</main>

app/views/shop_views/shop_info.html.erb
<%= render 'nav' %>


<main class="container-fluid">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="page-header">
      <h2>
        卖家登录信息
      </h2>
    </div>
    <h4>
      <strong>用户:</strong>
      <%= @seller.username %>
    </h4>

    <h4>
      <strong>密码:</strong>
      <%= @seller.password %>
    </h4>

    <h4>
      <strong>Email:</strong>
      <%= @seller.email %>
    </h4>
    <td><%= link_to '卖家信息修改', edit_seller_path(@seller), class: "btn btn-success" %></td>

    <div class="page-header">
      <h2>
        商店信息
      </h2>
    </div>
    <h4>
      <strong>图标:</strong>
      <% if @image %>
        <%= image_tag 'default_avatar.png', size: '100x100' %>
      <% else %>
        <%= image_tag @shop.image, size: '100x100' %>

      <% end %>

    </h4>
    <br>
    <%= link_to '商店图标修改', shop_shop_image_update_path, class: "btn btn-success"%>
    <h4>
      <strong>商店名:</strong>
      <%= @shop.name %>
    </h4>
    <h4>
      <strong>商店地址:</strong>
      <%= @shop.address %>
    </h4>
    <h4>
      <strong>详细描述:</strong>
      <%= @shop.description %>
    </h4>
    <h4>
      <strong>联系电话:</strong>
      <%= @shop.telephone %>
    </h4>
    <br>
    <td><%= link_to '修改商店信息', edit_shop_path(@shop), class: "btn btn-success" %></td>

  </div>
  <div class="col-sm-2"></div>

</main>

app/views/shop_views/shop_register.html.erb
<style>
    body {
        background-repeat: no-repeat;
        background-size: 100%;
        background-position: 0 -280px;
    }
</style>

<!-- 主体部分 -->
<main style="margin-top: 70px;">
  <div class="container">
    <div class="row">

      <div class="col-md-6 col-md-offset-3"
           style="border: 1px solid #ddd; border-radius: 2%; background-color: rgb(253, 252, 252);">
        <h3 style="text-align: center; margin-bottom: 20px;">完善信息</h3>
        <h4 style="color: #777777; font-size: 1em;">第一次登陆需要完善信息</h4>
        <div id="prompt">

        </div>
        <%= form_with url: shop_do_shop_register_path do %>
          <div class="form-group">
            <label class="control-label">店铺名称</label>
            <%= text_field_tag :name, nil, class:"form-control"%>
          </div>
          <div class="form-group">
            <label class="control-label">店铺地址</label>
            <%= text_field_tag :address, nil, class:"form-control"%>
          </div>
          <div class="form-group">
            <label class="control-label">店铺描述</label>
            <%= text_field_tag :description, nil, class:"form-control"%>
          </div>
          <div class="form-group">
            <label class="control-label">联系电话</label>
            <%= text_field_tag :phone, nil, class:"form-control"%>
          </div>
          <%= submit_tag 'login', class: "btn btn-success" %>
        <% end %>


        <p><a href="<%= shop_logout_path %>">退出登录</a></p>

      </div>
    </div>
  </div>
</main>

app/views/shop_views/upload_image.html.erb
<%= render 'nav' %>
<%= form_with url: do_product_image_update_path(@product), multipart: true do %>
  <%= file_field_tag :picture %>
  <%= submit_tag '更新' %>
<% end %>